language: c

# https://riptutorial.com/cmake/example/4723/configure-travis-ci-with-newest-cmake
# the install step will take care of deploying a newer cmake version
install:    
  # first we create a directory for the CMake binaries
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mkdir ${DEPS_DIR} && cd ${DEPS_DIR}; fi
  # we use wget to fetch the cmake binaries
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.16.4/cmake-3.16.4-Linux-x86_64.tar.gz; fi
  # this is optional, but useful:
  # do a quick md5 check to ensure that the archive we downloaded did not get compromised
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then echo "12a577aa04b6639766ae908f33cf70baefc11ac4499b8b1c8812d99f05fb6a02 *cmake-3.16.4-Linux-x86_64.tar.gz" > cmake_hash.txt; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sha256sum -c cmake_hash.txt; fi
  # extract the binaries; the output here is quite lengthy,
  # so we swallow it to not clutter up the travis console
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then tar -xvf cmake-3.16.4-Linux-x86_64.tar.gz > /dev/null; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mv cmake-3.16.4-Linux-x86_64.tar.gz cmake-install; fi
  # add both the top-level directory and the bin directory from the archive
  # to the system PATH. By adding it to the front of the path we hide the
  # preinstalled CMake with our own.
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH; fi
  # don't forget to switch back to the main build directory once you are done
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd ${TRAVIS_BUILD_DIR}; fi

os:
  - linux
#  - osx

compiler:
#  - clang
  - gcc

env:
  - FLAGS="-DCMAKE_BUILD_TYPE=Debug" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=ON"
  - FLAGS="-DCMAKE_BUILD_TYPE=Debug" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=OFF"
  - FLAGS="-DCMAKE_BUILD_TYPE=Release" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=ON"
  - FLAGS="-DCMAKE_BUILD_TYPE=Release" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=OFF"

script:
  - cmake --version
  - cmake -B build $FLAGS $VARYSINGLE .
  - cmake --build build
  - cd build && ctest && cpack -G "TGZ"

addons:
  apt:
    packages:
    - doxygen
    - doxygen-latex
    - graphviz
    sources:
     - george-edison55-precise-backports
