language: c

# https://github.com/LunarG/VulkanSamples/blob/master/.travis.yml
# https://riptutorial.com/cmake/example/4723/configure-travis-ci-with-newest-cmake
install:
  - set -e
  - CMAKE_VERSION=3.16.4
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.*}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      echo CMAKE_URL=${CMAKE_URL}
      mkdir cmake-${CMAKE_VERSION} && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake-${CMAKE_VERSION}
      export PATH=${PWD}/cmake-${CMAKE_VERSION}/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
    cmake --version

os:
  - linux
  - osx

compiler:
#  - clang
  - gcc

env:
  - FLAGS="-DCMAKE_BUILD_TYPE=Debug" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=ON"
#  - FLAGS="-DCMAKE_BUILD_TYPE=Debug" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=OFF"
#  - FLAGS="-DCMAKE_BUILD_TYPE=Release" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=ON"
#  - FLAGS="-DCMAKE_BUILD_TYPE=Release" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=OFF"

script:
  - cmake --version
  - cmake -B build $FLAGS $VARYSINGLE .
  - cmake --build build
  - cd build && ctest && cpack -G "TGZ"

addons:
  apt:
    packages:
    - doxygen
    - doxygen-latex
    - graphviz
    sources:
     - george-edison55-precise-backports
