language: c

sudo: false

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - FLAGS="-DCMAKE_BUILD_TYPE=Debug" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=ON"
  - FLAGS="-DCMAKE_BUILD_TYPE=Debug" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=OFF"
  - FLAGS="-DCMAKE_BUILD_TYPE=Release" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=ON"
  - FLAGS="-DCMAKE_BUILD_TYPE=Release" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=OFF"

script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -trace --warn-uninitialized --warn-unused_vars -Wdev -G "Unix Makefiles" .. -DCMAKE_INSTALL_PREFIX=../install -DHYPATIA_BUILD_STATIC=ON -DHYPATIA_BUILD_SHARED=ON $FLAGS $VARYSINGLE
  - make && ctest && make install && cpack -G "TGZ"

addons:
  apt:
    packages:
    - cmake3
    - doxygen
    - doxygen-latex
    - graphviz
    sources:
    - kalakris-cmake
