language: c

install:
  - set -e
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_VERSION=3.16.4
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.*}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      echo CMAKE_URL=${CMAKE_URL}
      mkdir cmake-${CMAKE_VERSION} && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake-${CMAKE_VERSION}
      export PATH=${PWD}/cmake-${CMAKE_VERSION}/bin:${PATH}
    else
      brew upgrade cmake
      brew unlink python@2
      brew install doxygen graphviz
    fi
    cmake --version

os:
  - linux
# - osx

compiler:
  - clang
  - gcc

env:
  - FLAGS="-DCMAKE_BUILD_TYPE=Debug" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=ON"
  - FLAGS="-DCMAKE_BUILD_TYPE=Debug" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=OFF"
  - FLAGS="-DCMAKE_BUILD_TYPE=Release" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=ON"
  - FLAGS="-DCMAKE_BUILD_TYPE=Release" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=OFF"

script:
  - cmake --version
  - cmake -B build $FLAGS $VARYSINGLE .
  - cmake --build build
  - cd build && ctest && cpack -G "TGZ"

addons:
  apt:
    packages:
    - cmake
    - cmake-data
    - doxygen
    - doxygen-latex
    - graphviz
    sources:
    - kalakris-cmake
    - george-edison55-precise-backports
