language: c

sudo: false

os:
  - linux
  - osx
  
compiler:
  - clang
  - gcc
  
env:
  - FLAGS="-DCMAKE_BUILD_TYPE=Debug" VARYSINGLE="-DHYPATIA_USE_SINGLE=0"
  - FLAGS="-DCMAKE_BUILD_TYPE=Debug" VARYSINGLE="-DHYPATIA_USE_SINGLE=0"
  - FLAGS="-DCMAKE_BUILD_TYPE=Release" VARYSINGLE="-DHYPATIA_USE_SINGLE=1"
  - FLAGS="-DCMAKE_BUILD_TYPE=Release" VARYSINGLE="-DHYPATIA_USE_SINGLE=1"

script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -trace --warn-uninitialized --warn-unused_vars -Wdev -G "Unix Makefiles" .. -DCMAKE_INSTALL_PREFIX=../install -DHYPATIA_BUILD_STATIC=1 -DHYPATIA_BUILD_SHARED=1 $FLAGS $VARYSINGLE
  - make && ctest && make install && cpack -G "TGZ"

addons:
  apt:
    packages:
    - cmake
    - doxygen
    - graphviz
