language: c

os:
  - linux
  - osx
  
compiler:
  - clang
  - gcc
  
env:
  - FLAGS="-DCMAKE_BUILD_TYPE=Debug"
  - FLAGS="-DCMAKE_BUILD_TYPE=Release"
  - VARYSINGLE="-DHYPATIA_USE_SINGLE=0"
  - VARYSINGLE="-DHYPATIA_USE_SINGLE=1"

cache: apt

script:
  - mkdir build
  - cd build
  - cmake -trace --warn-uninitialized --warn-unused_vars -Wdev -G "Unix Makefiles" .. -DCMAKE_INSTALL_PREFIX=../install -DHYPATIA_BUILD_STATIC=1 -DHYPATIA_BUILD_SHARED=1 $FLAGS $VARYSINGLE
  - make && ctest && make install && cpack -G "TGZ"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then sudo apt-get update; else brew update; fi
  - if [ $TRAVIS_OS_NAME == "linux" ]; then sudo apt-get install doxygen; else brew install doxygen; fi
  - if [ $TRAVIS_OS_NAME == "linux" ]; then sudo apt-get install graphviz; else brew install graphviz; fi

