language: c

sudo: false

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - FLAGS="-DCMAKE_BUILD_TYPE=Debug" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=ON"
  - FLAGS="-DCMAKE_BUILD_TYPE=Debug" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=OFF"
  - FLAGS="-DCMAKE_BUILD_TYPE=Release" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=ON"
  - FLAGS="-DCMAKE_BUILD_TYPE=Release" VARYSINGLE="-DHYPATIA_SINGLE_PRECISION_FLOATS=OFF"

script:
  - cmake --version
  - cmake -Bbuild -trace --warn-uninitialized --warn-unused_vars -Wdev $FLAGS $VARYSINGLE
  - cmake --build build
  - cd build && ctest && cpack -G "TGZ"

addons:
  apt:
    packages:
    - cmake
    - cmake-data
    - doxygen
    - doxygen-latex
    - graphviz
    sources:
    - kalakris-cmake
    - george-edison55-precise-backports
