shallow_clone: true

configuration:
 - Debug
 - Release

environment:
  matrix:
   - vstudio: Visual Studio 14 2015
   - vstudio: Visual Studio 12 2013
   - vstudio: Visual Studio 11 2012
   - vstudio: Visual Studio 10 2010
   - vstudio: Visual Studio 14 2015 Win64
   - vstudio: Visual Studio 12 2013 Win64
   - vstudio: Visual Studio 11 2012 Win64
   - vstudio: Visual Studio 10 2010 Win64

build_script:
 - mkdir build
 - cd build
 - cmake -G "%vstudio%" -trace --warn-uninitialized --warn-unused_vars -Wdev
   --config %configuration%
   -DCMAKE_BUILD_TYPE=%configuration%
   -DCMAKE_INSTALL_PREFIX=../install
   -DHYPATIA_BUILD_STATIC=1
   -DHYPATIA_BUILD_SHARED=1
   -DHYPATIA_BUILD_DOCS=0
   -DHYPATIA_USE_SINGLE=0
   ..
 - cmake --build "%cd%" --config %configuration%
 - cmd: '"c:\Program Files (x86)\CMake\bin\cpack.exe" -G "ZIP" -C %configuration%'

test_script:
 - ctest --output-on-failure
   -C %configuration%

artifacts:
 - path: 'build\*.zip'
 
