image:
  - Visual Studio 2019
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013
  - macos
  - macos-mojave
  - Ubuntu

build_script:
 - cmake --version
 - cmake -Bbuild
 - cmake --build build

test_script:
 - cd build
 - ctest -C Debug

