
environment:
  matrix:
   - vstudio: Visual Studio 14 2019
   - vstudio: Visual Studio 14 2017
   - vstudio: Visual Studio 14 2015
   - vstudio: Visual Studio 10 2010
   - vstudio: Visual Studio 14 2015 Win64
   - vstudio: Visual Studio 10 2010 Win64

build_script:
 - cmake --version
 - cmake -B build -G "%vstudio%" .
 - cmake --build build

test_script:
 - cd build
 - ctest -C Debug
