/* hypatia's short alias macros clash with GLM and cglm names */
#undef m2_add
#undef m2_equals
#undef m2_identity
#undef m2_mul
#undef m2_rotate
#undef m2_scalev2
#undef m2_set
#undef m2_sub
#undef m2_transpose
#undef m2_zero
#undef m3
#undef m3_add
#undef m3_equals
#undef m3_identity
#undef m3_mul
#undef m3_rotate
#undef m3_scalev2
#undef m3_set
#undef m3_sub
#undef m3_translatev2
#undef m3_transpose
#undef m3_zero
#undef m4
#undef m4_add
#undef m4_equals
#undef m4_identity
#undef m4_mul
#undef m4_rotatev3
#undef m4_scalev3
#undef m4_set
#undef m4_sub
#undef m4_translatev3
#undef m4_transpose
#undef m4_zero
#undef mat2
#undef mat2_add
#undef mat2_equals
#undef mat2_identity
#undef mat2_mul
#undef mat2_rotate
#undef mat2_scalev2
#undef mat2_set
#undef mat2_sub
#undef mat2_transpose
#undef mat2_zero
#undef mat3
#undef mat3_add
#undef mat3_equals
#undef mat3_identity
#undef mat3_mul
#undef mat3_rotate
#undef mat3_scalev2
#undef mat3_set
#undef mat3_sub
#undef mat3_translatev2
#undef mat3_transpose
#undef mat3_zero
#undef mat4
#undef mat4_add
#undef mat4_equals
#undef mat4_identity
#undef mat4_mul
#undef mat4_rotatev3
#undef mat4_scalev3
#undef mat4_set
#undef mat4_sub
#undef mat4_translatev3
#undef mat4_transpose
#undef mat4_zero
#undef matrix4_get_translation_EXP
#undef matrix4_make_transformation_rotationv3_EXP
#undef matrix4_multiplyv3_EXP
#undef matrix4_projection_ortho3d_rh_EXP
#undef matrix4_projection_perspective_fovy_rh_EXP
#undef matrix4_set_from_axisf3_angle_EXP
#undef matrix4_set_from_axisv3_angle_EXP
#undef matrix4_set_from_euler_anglesf3_EXP
#undef matrix4_transformation_compose_EXP
#undef matrix4_transformation_decompose_EXP
#undef matrix4_view_lookat_rh_EXP
#undef quat
#undef quat_equals
#undef quat_identity
#undef quat_lerp
#undef quat_nlerp
#undef quat_slerp
#undef quaternion_angle_between_EXP
#undef quaternion_difference_EXP
#undef quaternion_rotate_by_axis_angle_EXP
#undef quaternion_rotate_by_euler_angles_EXP
#undef quaternion_rotate_by_quaternion_EXP
#undef scalar_equals
#undef vec2
#undef vec3
#undef vec4
#undef vector2_length
#undef vector3_length
#undef vector4_length
